
DROP TABLE IF EXISTS stock_index_component_hs300;
CREATE TABLE IF NOT EXISTS stock_index_component_hs300(
   code VARCHAR(20) COMMENT '代码',
   name VARCHAR(50) NOT NULL COMMENT '名称',
   sync_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '同步时间',
   PRIMARY KEY ( code )
) COMMENT='沪深300成分股' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
